apiVersion: v1
  kind: Service
  metadata:
    name: {{ include "nginx-app.fullname" . }}
    labels:
      {{- include "nginx-app.labels" . | nindent 4 }}
  spec:
    ports:
      - port: {{ .Values.service.port }}
        targetPort: http
        protocol: TCP
        name: http
    selector:
      {{- include "nginx-app.selectorLabels" . | nindent 4 }}
    type: ClusterIP