name: Terraform CI/CD

on:
#   push:
#     branches:
#       - main
  pull_request:
    branches:
      - master

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_LAB }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_LAB }}
        AWS_REGION: ${{ vars.AWS_REGION_LAB }}

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      # Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: environments/lab

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan
    
      # Comment the Plan on Pull Requests
      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('tfplan', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### Terraform Plan\n\`\`\`\n${plan}\n\`\`\``
            });

      # Manual Approval for Apply (on push to main)
      - name: Manual Approval
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: "your-github-username" # Replace with your GitHub username
          minimum-approvals: 1
          issue-title: "Deploying Terraform Changes to Main"
          issue-body: "Please review the Terraform plan and approve or deny the deployment."

      # Terraform Apply (on push to main after approval)
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
